version: "3.1"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog
      MYSQL_USER: alchemist
      MYSQL_PASSWORD: secret
    ports:
      - "127.0.0.1:3307:3306"